### ISSUE TITLE
Icon in taskbar showing command prompt

### ISSUE THREAD

**Issue by kkuhle** [emavgl/windows-bash-contextmenu#1]
First off, thanks for writing this and making it available.  It is really nice

I was wondering if there was a way that you could make the icon in the taskbar show as the ubuntu icon as if you run "Bash on Ubuntu Windows" rather than it showing the cmd icon

**Comment by emavgl** [comment]
Hi, I'm working on it.
If you don't mind seeing for some milliseconds another terminal, I think that you could use this command:  
`cmd.exe /s /k pushd "%V" & start "" "%%USERPROFILE%%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Bash in Ubuntu on Windows.lnk" & exit`  

in order to use the standard Ubuntu Terminal shortcut. In this way you will have the icon and terminal's color-scheme as you launch the bash from the Windows Start Menu.

I don't have any other solution. But I think that this is pretty simple. I'm considering to commit it.

**Comment by kkuhle** [comment]
This sounds great.  I don't think having to wait milliseconds would be a bad thing at all.  I am trying to modify the bat file, but I'm not sure I'm doing it right.  Maybe you could commit or provide a new bat that I could test with?

**Comment by emavgl** [comment]
Hi, I've pushed a new version of the script. 
You have to download the entire folder or git clone this repo (don't forget to download also the .lnk file).
The new installation-script copies the new shortcut in the same folder of the standard shortcut and use it as I explained before. I couldn't use the standard shortcut because it opens the bash into the home directory. Anyway, now you can set its color-scheme and have the icon too.

If you want to use the standard shortcut please consider to change the .lnk has follow:
1. Go to C:\Users<your-user>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2. Edit the link "Bash in Ubuntu on Windows"
3. Remove the ~
![cattura](https://cloud.githubusercontent.com/assets/6958722/17629796/9ad63dce-60bc-11e6-8958-3de168da222e.PNG)

and use this installation script:

```
@ECHO OFF

set "command=cmd.exe /s /k pushd \"%%V\" & start \"\" \"%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Bash in Ubuntu on Windows.lnk\" & exit"

REG ADD HKCR\Directory\shell\bash\ /ve /d "Open in Bash"
REG ADD HKCR\Directory\shell\bash\command /ve /d "%command%"
REG ADD HKCR\Directory\shell\bash /v icon /d "%USERPROFILE%\AppData\Local\lxss\bash.ico"

REG ADD HKCR\Drive\shell\bash\ /ve /d "Open in Bash"
REG ADD HKCR\Drive\shell\bash\command /ve /d "%command%"
REG ADD HKCR\Drive\shell\bash /v icon /d "%USERPROFILE%\AppData\Local\lxss\bash.ico"

REG ADD HKCR\Directory\Background\shell\bash\ /ve /d "Open in Bash"
REG ADD HKCR\Directory\Background\shell\bash\command /ve /d "%command%"
REG ADD HKCR\Directory\Background\shell\bash /v icon /d "%USERPROFILE%\AppData\Local\lxss\bash.ico"
```

Let me know! :smile:

**Comment by kkuhle** [comment]
I've tested this and it is so much better!  Having this, I don't anticipate I'll ever load a bash terminal from the start menu so I've just modified the Bash in Ubuntu on Windows.lnk so that it works with the default one and takes my changes that I've made.  Thanks for your work on this!

**Comment by emavgl** [comment]
Great! Thanks for your suggestions.
I have some changes in mind. Don't forget to give a ⭐ to the project and follow the development. 😄
